.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SIMPLE\-ERD" "1" "April 2017" "" ""
.
.SH "NAME"
\fBsimple\-erd\fR \- simple ERD generator
.
.SH "SYNOPSIS"
\fBsimple\-erd\fR \fB\-i\fR input_path \fB\-o\fR input_path
.
.SH "DESCRIPTION"
SimpleERD is a tool to generate beautif ERD diagrams based on plaintext input\.
.
.SH "OPTIONS"
.
.TP
\fB\-i\fR input_path
Specify path to input file\.
.
.TP
\fB\-o\fR output_path
Specify path to ouput file\.
.
.SH "AUTHORS"
SimpleERD is maintained by Eugene Pirogov\.
.
.SH "REPORTING BUGS"
Visit \fIhttps://github\.com/gmile/simple\-erd/issues\fR\.
